# modules/report.py

import pandas as pd
import streamlit as st
from fpdf import FPDF
import io
from datetime import datetime

# ─────────────────────────────
# Helper function to remove emojis
# ─────────────────────────────
def clean_text(text):
    """
    Remove emojis and special characters
    that PDF font cannot support
    """
    if not isinstance(text, str):
        text = str(text)
    
    # Encode to ascii and ignore unsupported characters
    clean = text.encode("ascii", "ignore").decode("ascii")
    return clean.strip()


class CleaningReport(FPDF):
    
    def header(self):
        self.set_font("Helvetica", "B", 20)
        self.set_fill_color(67, 97, 238)
        self.set_text_color(255, 255, 255)
        self.cell(
            0, 15,
            "SmartClean - Data Cleaning Report",
            border=False,
            ln=True,
            align="C",
            fill=True
        )
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(
            0, 10,
            f"Generated by SmartClean | "
            f"Page {self.page_no()}",
            align="C"
        )


def generate_pdf_report(
    original_df,
    clean_df,
    health_score,
    cleaning_report,
    file_name
):
    
    pdf = CleaningReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # ─────────────────────────────
    # Section 1: File Info
    # ─────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(67, 97, 238)
    pdf.cell(0, 10, "1. File Information", ln=True)
    
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    info = [
        ["File Name", clean_text(file_name)],
        ["Cleaned On", now],
        ["Original Rows", str(len(original_df))],
        ["Original Columns", str(len(original_df.columns))],
    ]
    
    for label, value in info:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(60, 8, label + ":", ln=False)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, value, ln=True)
    
    pdf.ln(5)
    
    # ─────────────────────────────
    # Section 2: Health Score
    # ─────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(67, 97, 238)
    pdf.cell(0, 10, "2. Dataset Health Score", ln=True)
    
    pdf.set_font("Helvetica", "B", 24)
    
    if health_score >= 80:
        pdf.set_text_color(0, 200, 0)
    elif health_score >= 50:
        pdf.set_text_color(255, 165, 0)
    else:
        pdf.set_text_color(255, 0, 0)
    
    pdf.cell(0, 12, f"{health_score}% Healthy", ln=True)
    pdf.ln(3)
    
    # ─────────────────────────────
    # Section 3: Before vs After
    # ─────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(67, 97, 238)
    pdf.cell(0, 10, "3. Before vs After Comparison", ln=True)
    
    # Table header
    pdf.set_fill_color(67, 97, 238)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(70, 9, "Metric", border=1, fill=True)
    pdf.cell(55, 9, "Before", border=1, fill=True)
    pdf.cell(55, 9, "After", border=1, fill=True, ln=True)
    
    # Table rows
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 11)
    
    rows = [
        [
            "Total Rows",
            str(len(original_df)),
            str(len(clean_df))
        ],
        [
            "Missing Values",
            str(original_df.isnull().sum().sum()),
            str(clean_df.isnull().sum().sum())
        ],
        [
            "Duplicate Rows",
            str(original_df.duplicated().sum()),
            str(clean_df.duplicated().sum())
        ],
        [
            "Total Columns",
            str(len(original_df.columns)),
            str(len(clean_df.columns))
        ],
    ]
    
    for i, row in enumerate(rows):
        if i % 2 == 0:
            pdf.set_fill_color(240, 240, 255)
        else:
            pdf.set_fill_color(255, 255, 255)
            
        pdf.cell(70, 8, row[0], border=1, fill=True)
        pdf.cell(55, 8, row[1], border=1, fill=True)
        pdf.cell(55, 8, row[2], border=1, fill=True, ln=True)
    
    pdf.ln(5)
    
    # ─────────────────────────────
    # Section 4: Cleaning Actions
    # ─────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(67, 97, 238)
    pdf.cell(0, 10, "4. Cleaning Actions Performed", ln=True)
    
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    
    if cleaning_report:
        for action in cleaning_report:
            # Remove emojis from action text
            clean_action = clean_text(action)
            pdf.cell(10, 8, "-", ln=False)
            pdf.cell(0, 8, clean_action, ln=True)
    else:
        pdf.cell(0, 8, "No cleaning actions performed", ln=True)
    
    pdf.ln(5)
    
    # ─────────────────────────────
    # Section 5: Column Details
    # ─────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(67, 97, 238)
    pdf.cell(0, 10, "5. Column Details", ln=True)
    
    # Table header
    pdf.set_fill_color(67, 97, 238)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(50, 9, "Column Name", border=1, fill=True)
    pdf.cell(35, 9, "Data Type", border=1, fill=True)
    pdf.cell(35, 9, "Missing", border=1, fill=True)
    pdf.cell(35, 9, "Unique Values", border=1, fill=True)
    pdf.cell(25, 9, "Outliers", border=1, fill=True, ln=True)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 10)
    
    for i, col in enumerate(clean_df.columns):
        
        missing = clean_df[col].isnull().sum()
        missing_pct = round(
            (missing / len(clean_df)) * 100, 1
        )
        unique = clean_df[col].nunique()
        
        outliers = 0
        if clean_df[col].dtype in ['int64', 'float64']:
            Q1 = clean_df[col].quantile(0.25)
            Q3 = clean_df[col].quantile(0.75)
            IQR = Q3 - Q1
            outliers = len(clean_df[col][
                (clean_df[col] < Q1 - 1.5 * IQR) |
                (clean_df[col] > Q3 + 1.5 * IQR)
            ])
        
        if i % 2 == 0:
            pdf.set_fill_color(240, 240, 255)
        else:
            pdf.set_fill_color(255, 255, 255)
        
        # Clean column name also
        clean_col = clean_text(str(col))[:20]
        
        pdf.cell(50, 8, clean_col, border=1, fill=True)
        pdf.cell(35, 8, str(clean_df[col].dtype), border=1, fill=True)
        pdf.cell(35, 8, f"{missing} ({missing_pct}%)", border=1, fill=True)
        pdf.cell(35, 8, str(unique), border=1, fill=True)
        pdf.cell(25, 8, str(outliers), border=1, fill=True, ln=True)
    
    return bytes(pdf.output())


def generate_excel_report(
    original_df,
    clean_df,
    health_score,
    cleaning_report,
    file_name
):
    
    buffer = io.BytesIO()
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
        
        summary_data = {
            "Metric": [
                "File Name",
                "Cleaned On",
                "Health Score",
                "Original Rows",
                "Cleaned Rows",
                "Rows Removed",
                "Original Missing Values",
                "Cleaned Missing Values",
                "Duplicate Rows Removed"
            ],
            "Value": [
                file_name,
                now,
                f"{health_score}%",
                len(original_df),
                len(clean_df),
                len(original_df) - len(clean_df),
                original_df.isnull().sum().sum(),
                clean_df.isnull().sum().sum(),
                original_df.duplicated().sum()
            ]
        }
        
        summary_df = pd.DataFrame(summary_data)
        summary_df.to_excel(
            writer,
            sheet_name="Summary",
            index=False
        )
        
        actions_df = pd.DataFrame({
            "Cleaning Actions": cleaning_report
        })
        actions_df.to_excel(
            writer,
            sheet_name="Cleaning Actions",
            index=False
        )
        
        col_details = []
        for col in clean_df.columns:
            missing = clean_df[col].isnull().sum()
            missing_pct = round(
                (missing / len(clean_df)) * 100, 1
            )
            
            outliers = 0
            if clean_df[col].dtype in ['int64', 'float64']:
                Q1 = clean_df[col].quantile(0.25)
                Q3 = clean_df[col].quantile(0.75)
                IQR = Q3 - Q1
                outliers = len(clean_df[col][
                    (clean_df[col] < Q1 - 1.5 * IQR) |
                    (clean_df[col] > Q3 + 1.5 * IQR)
                ])
            
            col_details.append({
                "Column": col,
                "Data Type": str(clean_df[col].dtype),
                "Missing Count": missing,
                "Missing %": f"{missing_pct}%",
                "Unique Values": clean_df[col].nunique(),
                "Outliers": outliers
            })
        
        col_df = pd.DataFrame(col_details)
        col_df.to_excel(
            writer,
            sheet_name="Column Details",
            index=False
        )
        
        clean_df.to_excel(
            writer,
            sheet_name="Clean Data",
            index=False
        )
    
    return buffer.getvalue()
